package com.essam.chatapp.ui.contacts.utils;

import android.app.Activity;
import android.database.Cursor;
import android.net.Uri;
import android.provider.ContactsContract;
import android.util.Log;

import java.util.HashMap;
import java.util.Map;

public class ContactsHelper {
    public static String getPhone(String code) {
        return countryToPhonePrefix.get(code.toUpperCase());
    }

    public static Map<String, String> getAll(){
        return countryToPhonePrefix;
    }

    private static Map<String, String> countryToPhonePrefix = new HashMap<>();

    static {
        countryToPhonePrefix.put("AF", "+93");
        countryToPhonePrefix.put("AL", "+355");
        countryToPhonePrefix.put("DZ", "+213");
        countryToPhonePrefix.put("AD", "+376");
        countryToPhonePrefix.put("AO", "+244");
        countryToPhonePrefix.put("AG", "+1-268");
        countryToPhonePrefix.put("AR", "+54");
        countryToPhonePrefix.put("AM", "+374");
        countryToPhonePrefix.put("AU", "+61");
        countryToPhonePrefix.put("AT", "+43");
        countryToPhonePrefix.put("AZ", "+994");
        countryToPhonePrefix.put("BS", "+1-242");
        countryToPhonePrefix.put("BH", "+973");
        countryToPhonePrefix.put("BD", "+880");
        countryToPhonePrefix.put("BB", "+1-246");
        countryToPhonePrefix.put("BY", "+375");
        countryToPhonePrefix.put("BE", "+32");
        countryToPhonePrefix.put("BZ", "+501");
        countryToPhonePrefix.put("BJ", "+229");
        countryToPhonePrefix.put("BT", "+975");
        countryToPhonePrefix.put("BO", "+591");
        countryToPhonePrefix.put("BA", "+387");
        countryToPhonePrefix.put("BW", "+267");
        countryToPhonePrefix.put("BR", "+55");
        countryToPhonePrefix.put("BN", "+673");
        countryToPhonePrefix.put("BG", "+359");
        countryToPhonePrefix.put("BF", "+226");
        countryToPhonePrefix.put("BI", "+257");
        countryToPhonePrefix.put("KH", "+855");
        countryToPhonePrefix.put("CM", "+237");
        countryToPhonePrefix.put("CA", "+1");
        countryToPhonePrefix.put("CV", "+238");
        countryToPhonePrefix.put("CF", "+236");
        countryToPhonePrefix.put("TD", "+235");
        countryToPhonePrefix.put("CL", "+56");
        countryToPhonePrefix.put("CN", "+86");
        countryToPhonePrefix.put("CO", "+57");
        countryToPhonePrefix.put("KM", "+269");
        countryToPhonePrefix.put("CD", "+243");
        countryToPhonePrefix.put("CG", "+242");
        countryToPhonePrefix.put("CR", "+506");
        countryToPhonePrefix.put("CI", "+225");
        countryToPhonePrefix.put("HR", "+385");
        countryToPhonePrefix.put("CU", "+53");
        countryToPhonePrefix.put("CY", "+357");
        countryToPhonePrefix.put("CZ", "+420");
        countryToPhonePrefix.put("DK", "+45");
        countryToPhonePrefix.put("DJ", "+253");
        countryToPhonePrefix.put("DM", "+1-767");
        countryToPhonePrefix.put("DO", "+1-809and1-829");
        countryToPhonePrefix.put("EC", "+593");
        countryToPhonePrefix.put("EG", "+2");
        countryToPhonePrefix.put("SV", "+503");
        countryToPhonePrefix.put("GQ", "+240");
        countryToPhonePrefix.put("ER", "+291");
        countryToPhonePrefix.put("EE", "+372");
        countryToPhonePrefix.put("ET", "+251");
        countryToPhonePrefix.put("FJ", "+679");
        countryToPhonePrefix.put("FI", "+358");
        countryToPhonePrefix.put("FR", "+33");
        countryToPhonePrefix.put("GA", "+241");
        countryToPhonePrefix.put("GM", "+220");
        countryToPhonePrefix.put("GE", "+995");
        countryToPhonePrefix.put("DE", "+49");
        countryToPhonePrefix.put("GH", "+233");
        countryToPhonePrefix.put("GR", "+30");
        countryToPhonePrefix.put("GD", "+1-473");
        countryToPhonePrefix.put("GT", "+502");
        countryToPhonePrefix.put("GN", "+224");
        countryToPhonePrefix.put("GW", "+245");
        countryToPhonePrefix.put("GY", "+592");
        countryToPhonePrefix.put("HT", "+509");
        countryToPhonePrefix.put("HN", "+504");
        countryToPhonePrefix.put("HU", "+36");
        countryToPhonePrefix.put("IS", "+354");
        countryToPhonePrefix.put("IN", "+91");
        countryToPhonePrefix.put("ID", "+62");
        countryToPhonePrefix.put("IR", "+98");
        countryToPhonePrefix.put("IQ", "+964");
        countryToPhonePrefix.put("IE", "+353");
        countryToPhonePrefix.put("IL", "+972");
        countryToPhonePrefix.put("IT", "+39");
        countryToPhonePrefix.put("JM", "+1-876");
        countryToPhonePrefix.put("JP", "+81");
        countryToPhonePrefix.put("JO", "+962");
        countryToPhonePrefix.put("KZ", "+7");
        countryToPhonePrefix.put("KE", "+254");
        countryToPhonePrefix.put("KI", "+686");
        countryToPhonePrefix.put("KP", "+850");
        countryToPhonePrefix.put("KR", "+82");
        countryToPhonePrefix.put("KW", "+965");
        countryToPhonePrefix.put("KG", "+996");
        countryToPhonePrefix.put("LA", "+856");
        countryToPhonePrefix.put("LV", "+371");
        countryToPhonePrefix.put("LB", "+961");
        countryToPhonePrefix.put("LS", "+266");
        countryToPhonePrefix.put("LR", "+231");
        countryToPhonePrefix.put("LY", "+218");
        countryToPhonePrefix.put("LI", "+423");
        countryToPhonePrefix.put("LT", "+370");
        countryToPhonePrefix.put("LU", "+352");
        countryToPhonePrefix.put("MK", "+389");
        countryToPhonePrefix.put("MG", "+261");
        countryToPhonePrefix.put("MW", "+265");
        countryToPhonePrefix.put("MY", "+60");
        countryToPhonePrefix.put("MV", "+960");
        countryToPhonePrefix.put("ML", "+223");
        countryToPhonePrefix.put("MT", "+356");
        countryToPhonePrefix.put("MH", "+692");
        countryToPhonePrefix.put("MR", "+222");
        countryToPhonePrefix.put("MU", "+230");
        countryToPhonePrefix.put("MX", "+52");
        countryToPhonePrefix.put("FM", "+691");
        countryToPhonePrefix.put("MD", "+373");
        countryToPhonePrefix.put("MC", "+377");
        countryToPhonePrefix.put("MN", "+976");
        countryToPhonePrefix.put("ME", "+382");
        countryToPhonePrefix.put("MA", "+212");
        countryToPhonePrefix.put("MZ", "+258");
        countryToPhonePrefix.put("MM", "+95");
        countryToPhonePrefix.put("NA", "+264");
        countryToPhonePrefix.put("NR", "+674");
        countryToPhonePrefix.put("NP", "+977");
        countryToPhonePrefix.put("NL", "+31");
        countryToPhonePrefix.put("NZ", "+64");
        countryToPhonePrefix.put("NI", "+505");
        countryToPhonePrefix.put("NE", "+227");
        countryToPhonePrefix.put("NG", "+234");
        countryToPhonePrefix.put("NO", "+47");
        countryToPhonePrefix.put("OM", "+968");
        countryToPhonePrefix.put("PK", "+92");
        countryToPhonePrefix.put("PW", "+680");
        countryToPhonePrefix.put("PA", "+507");
        countryToPhonePrefix.put("PG", "+675");
        countryToPhonePrefix.put("PY", "+595");
        countryToPhonePrefix.put("PE", "+51");
        countryToPhonePrefix.put("PH", "+63");
        countryToPhonePrefix.put("PL", "+48");
        countryToPhonePrefix.put("PT", "+351");
        countryToPhonePrefix.put("QA", "+974");
        countryToPhonePrefix.put("RO", "+40");
        countryToPhonePrefix.put("RU", "+7");
        countryToPhonePrefix.put("RW", "+250");
        countryToPhonePrefix.put("KN", "+1-869");
        countryToPhonePrefix.put("LC", "+1-758");
        countryToPhonePrefix.put("VC", "+1-784");
        countryToPhonePrefix.put("WS", "+685");
        countryToPhonePrefix.put("SM", "+378");
        countryToPhonePrefix.put("ST", "+239");
        countryToPhonePrefix.put("SA", "+966");
        countryToPhonePrefix.put("SN", "+221");
        countryToPhonePrefix.put("RS", "+381");
        countryToPhonePrefix.put("SC", "+248");
        countryToPhonePrefix.put("SL", "+232");
        countryToPhonePrefix.put("SG", "+65");
        countryToPhonePrefix.put("SK", "+421");
        countryToPhonePrefix.put("SI", "+386");
        countryToPhonePrefix.put("SB", "+677");
        countryToPhonePrefix.put("SO", "+252");
        countryToPhonePrefix.put("ZA", "+27");
        countryToPhonePrefix.put("ES", "+34");
        countryToPhonePrefix.put("LK", "+94");
        countryToPhonePrefix.put("SD", "+249");
        countryToPhonePrefix.put("SR", "+597");
        countryToPhonePrefix.put("SZ", "+268");
        countryToPhonePrefix.put("SE", "+46");
        countryToPhonePrefix.put("CH", "+41");
        countryToPhonePrefix.put("SY", "+963");
        countryToPhonePrefix.put("TJ", "+992");
        countryToPhonePrefix.put("TZ", "+255");
        countryToPhonePrefix.put("TH", "+66");
        countryToPhonePrefix.put("TL", "+670");
        countryToPhonePrefix.put("TG", "+228");
        countryToPhonePrefix.put("TO", "+676");
        countryToPhonePrefix.put("TT", "+1-868");
        countryToPhonePrefix.put("TN", "+216");
        countryToPhonePrefix.put("TR", "+90");
        countryToPhonePrefix.put("TM", "+993");
        countryToPhonePrefix.put("TV", "+688");
        countryToPhonePrefix.put("UG", "+256");
        countryToPhonePrefix.put("UA", "+380");
        countryToPhonePrefix.put("AE", "+971");
        countryToPhonePrefix.put("GB", "+44");
        countryToPhonePrefix.put("US", "+1");
        countryToPhonePrefix.put("UY", "+598");
        countryToPhonePrefix.put("UZ", "+998");
        countryToPhonePrefix.put("VU", "+678");
        countryToPhonePrefix.put("VA", "+379");
        countryToPhonePrefix.put("VE", "+58");
        countryToPhonePrefix.put("VN", "+84");
        countryToPhonePrefix.put("YE", "+967");
        countryToPhonePrefix.put("ZM", "+260");
        countryToPhonePrefix.put("ZW", "+263");
        countryToPhonePrefix.put("TW", "+886");
        countryToPhonePrefix.put("CX", "+61");
        countryToPhonePrefix.put("CC", "+61");
        countryToPhonePrefix.put("NF", "+672");
        countryToPhonePrefix.put("NC", "+687");
        countryToPhonePrefix.put("PF", "+689");
        countryToPhonePrefix.put("YT", "+262");
        countryToPhonePrefix.put("GP", "+590");
        countryToPhonePrefix.put("PM", "+508");
        countryToPhonePrefix.put("WF", "+681");
        countryToPhonePrefix.put("CK", "+682");
        countryToPhonePrefix.put("NU", "+683");
        countryToPhonePrefix.put("TK", "+690");
        countryToPhonePrefix.put("GG", "+44");
        countryToPhonePrefix.put("IM", "+44");
        countryToPhonePrefix.put("JE", "+44");
        countryToPhonePrefix.put("AI", "+1-264");
        countryToPhonePrefix.put("BM", "+1-441");
        countryToPhonePrefix.put("IO", "+246");
        countryToPhonePrefix.put("", "+357");
        countryToPhonePrefix.put("VG", "+1-284");
        countryToPhonePrefix.put("KY", "+1-345");
        countryToPhonePrefix.put("FK", "+500");
        countryToPhonePrefix.put("GI", "+350");
        countryToPhonePrefix.put("MS", "+1-664");
        countryToPhonePrefix.put("SH", "+290");
        countryToPhonePrefix.put("TC", "+1-649");
        countryToPhonePrefix.put("MP", "+1-670");
        countryToPhonePrefix.put("PR", "+1-787and1-939");
        countryToPhonePrefix.put("AS", "+1-684");
        countryToPhonePrefix.put("GU", "+1-671");
        countryToPhonePrefix.put("VI", "+1-340");
        countryToPhonePrefix.put("HK", "+852");
        countryToPhonePrefix.put("MO", "+853");
        countryToPhonePrefix.put("FO", "+298");
        countryToPhonePrefix.put("GL", "+299");
        countryToPhonePrefix.put("GF", "+594");
        countryToPhonePrefix.put("MQ", "+596");
        countryToPhonePrefix.put("RE", "+262");
        countryToPhonePrefix.put("AX", "+358-18");
        countryToPhonePrefix.put("AW", "+297");
        countryToPhonePrefix.put("AN", "+599");
        countryToPhonePrefix.put("SJ", "+47");
        countryToPhonePrefix.put("AC", "+247");
        countryToPhonePrefix.put("TA", "+290");
        countryToPhonePrefix.put("CS", "+381");
        countryToPhonePrefix.put("PS", "+970");
        countryToPhonePrefix.put("EH", "+212");
    }

    public static String getContactName(Activity activity, String phoneNumber){
        Uri uri=Uri.withAppendedPath(ContactsContract.PhoneLookup.CONTENT_FILTER_URI,Uri.encode(phoneNumber));
        String[] projection = new String[]{ContactsContract.PhoneLookup.DISPLAY_NAME};

        Log.i("TAG", "getContactName: "+phoneNumber);
        String contactName = phoneNumber;
        if(activity != null && !contactName.isEmpty()) {
            Cursor cursor = activity.getContentResolver().query(uri, projection, null, null, null);

            if (cursor != null) {
                if (cursor.moveToFirst()) {
                    contactName = cursor.getString(0);
                }
                cursor.close();
            }
        }
        return contactName;
    }
}
